"""added one to many relationship to caretaker and dog

Revision ID: 3ffbe39a2d54
Revises: c0ec80c6bb37
Create Date: 2022-11-04 10:21:15.616463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffbe39a2d54'
down_revision = 'c0ec80c6bb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('caretaker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dog', 'caretaker', ['caretaker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dog', type_='foreignkey')
    op.drop_column('dog', 'caretaker_id')
    # ### end Alembic commands ###
