"""empty message

Revision ID: 9361cb27e189
Revises: 2e2e6e033048
Create Date: 2023-05-09 10:19:46.367481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9361cb27e189'
down_revision = '2e2e6e033048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crystal', sa.Column('healer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crystal', 'healer', ['healer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crystal', type_='foreignkey')
    op.drop_column('crystal', 'healer_id')
    # ### end Alembic commands ###
