"""dog and caretake models

Revision ID: c0ec80c6bb37
Revises: 
Create Date: 2022-11-04 10:07:49.027132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ec80c6bb37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dog_caretaker_id_fkey', 'dog', type_='foreignkey')
    op.drop_column('dog', 'caretaker_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('caretaker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dog_caretaker_id_fkey', 'dog', 'caretaker', ['caretaker_id'], ['id'])
    # ### end Alembic commands ###
